print("Введите текст: \n")
my_string = input()
print(my_string)
print(len(my_string), "- Символа в строке выше")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])